name: app_shop_ease
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
        sdk: flutter
  intl: any
  cupertino_icons: ^1.0.8
  gap: ^3.0.1
  flutter_dotenv: ^5.2.1
  flutter_screenutil: ^5.9.3
  firebase_core: ^3.8.1
  connectivity_plus: ^6.1.0
  get_it: ^8.0.2
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  flutter_svg: ^2.0.16
  google_fonts: ^6.2.1
  animate_do: ^3.3.4
  shared_preferences: ^2.3.3
  dartz: ^0.10.1
  dio: ^5.7.0
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  device_info_plus: ^11.2.0
  flutter_native_splash: ^2.4.4
  flutter_zoom_drawer: ^3.2.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env.dev
    - .env.prod
    - assets/images/
    - assets/icons/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
flutter_intl:
  enabled: true
  localizely:
    project_id: app
